# Generated by Django 3.2.12 on 2022-04-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_auto_20220414_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='price_plan',
            name='add',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='price_plan',
            name='download',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='price_plan',
            name='resolution',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='price_plan',
            name='sound',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='price_plan',
            name='sports',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
