# Generated by Django 3.2.12 on 2022-04-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0003_auto_20220414_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priceplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=50, unique=True)),
                ('plan_price', models.IntegerField()),
                ('plan_valid', models.IntegerField()),
                ('resolution', models.CharField(max_length=200, null=True, unique=True)),
                ('download', models.CharField(max_length=200, null=True, unique=True)),
                ('add', models.CharField(max_length=200, null=True, unique=True)),
                ('sports', models.CharField(max_length=200, null=True, unique=True)),
                ('sound', models.CharField(max_length=200, null=True, unique=True)),
            ],
        ),
    ]
