# Generated by Django 3.2.12 on 2022-04-14 10:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0004_priceplan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='price_Plan',
        ),
        migrations.AddField(
            model_name='priceplan',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
