# Generated by Django 3.2.12 on 2022-04-20 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0006_orderproduct_purchaseplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseplan',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='purchaseplan',
            name='user',
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
        migrations.DeleteModel(
            name='Purchaseplan',
        ),
    ]
