# Generated by Django 3.2.8 on 2022-04-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20220402_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='movie_release_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
