# Generated by Django 3.2.12 on 2022-04-16 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_total_movie'),
        ('store', '0007_alter_reviewrating_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Web',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('image', models.ImageField(upload_to='photos/products')),
                ('stock', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateField(auto_now=True)),
                ('movie_release_year', models.CharField(blank=True, max_length=200, null=True)),
                ('tmdb', models.CharField(blank=True, max_length=200, null=True)),
                ('web_director1', models.CharField(blank=True, max_length=200, null=True)),
                ('web_director2', models.CharField(blank=True, max_length=200, null=True)),
                ('web_writer1', models.CharField(blank=True, max_length=100, null=True)),
                ('web_writer2', models.CharField(blank=True, max_length=100, null=True)),
                ('web_producer1', models.CharField(blank=True, max_length=100, null=True)),
                ('web_producer2', models.CharField(blank=True, max_length=100, null=True)),
                ('web_actor1', models.CharField(blank=True, max_length=100, null=True)),
                ('actor1_name_in_movie', models.CharField(blank=True, max_length=100, null=True)),
                ('web_actor2', models.CharField(blank=True, max_length=100, null=True)),
                ('actor2_name_in_movie', models.CharField(blank=True, max_length=100, null=True)),
                ('web_actor3', models.CharField(blank=True, max_length=100, null=True)),
                ('actor3_name_in_movie', models.CharField(blank=True, max_length=100, null=True)),
                ('web_actor4', models.CharField(blank=True, max_length=100, null=True)),
                ('actor4_name_in_movie', models.CharField(blank=True, max_length=100, null=True)),
                ('web_actor5', models.CharField(blank=True, max_length=100, null=True)),
                ('actor5_name_in_movie', models.CharField(blank=True, max_length=100, null=True)),
                ('web_actor6', models.CharField(blank=True, max_length=100, null=True)),
                ('actor6_name_in_movie', models.CharField(blank=True, max_length=100, null=True)),
                ('web_actor1_image', models.ImageField(upload_to='photos/products/cast')),
                ('web_actor2_image', models.ImageField(upload_to='photos/products/cast')),
                ('web_actor3_image', models.ImageField(upload_to='photos/products/cast')),
                ('web_actor4_image', models.ImageField(upload_to='photos/products/cast')),
                ('web_actor5_image', models.ImageField(upload_to='photos/products/cast')),
                ('web_actor6_image', models.ImageField(upload_to='photos/products/cast')),
                ('movie_release_date', models.CharField(blank=True, max_length=20, null=True)),
                ('movie_link', models.URLField(max_length=5000)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
