# Generated by Django 3.2.12 on 2022-04-23 08:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_web'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bts_1',
            field=models.URLField(default=django.utils.timezone.now, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='bts_2',
            field=models.URLField(default=django.utils.timezone.now, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='bts_3',
            field=models.URLField(default=django.utils.timezone.now, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='bts_4',
            field=models.URLField(default=django.utils.timezone.now, max_length=5000),
            preserve_default=False,
        ),
    ]
