# Generated by Django 3.2.12 on 2022-04-25 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20220425_2257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='web',
            old_name='awards7',
            new_name='nominee_awards1',
        ),
        migrations.RenameField(
            model_name='web',
            old_name='awards8',
            new_name='nominee_awards2',
        ),
        migrations.RenameField(
            model_name='web',
            old_name='awards9',
            new_name='nominee_awards3',
        ),
    ]
