# Generated by Django 3.2.12 on 2022-04-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20220425_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bts_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bts_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bts_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bts_4',
        ),
        migrations.AddField(
            model_name='product',
            name='awards1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='awards2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='awards3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='awards4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='awards5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='awards6',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='nominee_awards1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='nominee_awards2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='nominee_awards3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
