# Generated by Django 3.1.5 on 2022-03-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='total_movie',
            field=models.IntegerField(default=100),
        ),
    ]
