# Generated by Django 3.2.12 on 2022-04-11 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0002_markitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='markitem',
            name='user',
        ),
    ]
