# Generated by Django 3.2.12 on 2022-04-12 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0004_markitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markitem',
            name='mark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marks.mark'),
        ),
    ]
